### ISSUE TITLE
soxr-python can't be found in conda-forge

### ISSUE THREAD

**Issue by giamic** [dofuuz/python-soxr#15]
I'm trying to install librosa 0.10 through conda (actually micromamba, but that shouldn't matter) but I receive the following error:
```
error    libmamba Could not solve for environment specs
    The following package could not be installed
    └─ librosa 0.10**  is uninstallable because it requires
       └─ soxr-python >=0.3.2 , which does not exist (perhaps a missing channel).
```
I am using conda-forge as a channel for packages. I tried adding the default one but nothing changed. This is unexpected because https://anaconda.org/conda-forge/soxr-python says that soxr-python 0.3.3 should be available on conda-forge.

I'm on a Mac M1, MacOS 13.3.1.

**Comment by dofuuz** [comment]
Curently, conda-forge soxr-python dose not provide osx-arm64 builds.
I'll update osx-arm64 build in near future.

If you are urgent, Install python-soxr(and librosa) from pip.

**Comment by dofuuz** [comment]
osx-arm64 builds added to conda-forge.
