### ISSUE TITLE
Installation Issue with Python-Soxr: AttributeError on 'version'

### ISSUE THREAD

**Issue by tlocd** [dofuuz/python-soxr#24]
### Problem Description

Encountered an installation issue while attempting to install Python-Soxr using the provided setup script. The installation process fails with the following error:

```bash
AttributeError: module 'soxr' has no attribute '__version__'
```

### Reproduction Steps

1. Clone the Python-Soxr repository: `git clone https://github.com/pytorch/audio.git`
2. Navigate to the Python-Soxr directory: `cd python-soxr`
3. Run the installation script: `sudo python3 setup.py install`

### Expected Behavior

Expect a successful installation of Python-Soxr without encountering the AttributeError related to the '__version__' attribute.

### Environment Information

- Operating System: Linux debian risc-v
- Python Version: 3.11
- Python-Soxr Version: (latest commit or release version)

**Comment by dofuuz** [comment]
Triggering setup.py wouldn't work.

Use pip to install python-soxr.

If you need manual build, follow build instruction here.
https://github.com/dofuuz/python-soxr/blob/main/BUILDING.md
