### ISSUE TITLE
How to get the delay of cysoxr?

### ISSUE THREAD

**Issue by pengzhendong** [dofuuz/python-soxr#26]
I want to cache the original audio, but I don't know how to get the soxr_delay of cysoxr?

**Comment by dofuuz** [comment]
It's not implemented in python-soxr.

May I ask why do you need soxr_delay? It's not needed unless doing low-delay real-time processing.

**Comment by pengzhendong** [comment]
Yes. I need streaming resampling  （48k=>16k) before streaming voice detection. 
I want to cache the original (48k) audio, but I don't konw how to set the buffer size. (I implement the soxr_delay，the value is 0）

**Comment by dofuuz** [comment]
You should add FIFO buffer to output if you need constant sample size.
