### ISSUE TITLE
NumPy 2 support, Next release plan

### ISSUE THREAD

**Issue by dofuuz** [dofuuz/python-soxr#28]
I'm going to introduce NumPy 2 in next release.

Next release will be major overhaul for python-soxr.
- Change C binding to [nanobind](https://github.com/wjakob/nanobind)
  - SIMD64 support (faster VHQ mode)
- Python 3.13
- NumPy 2
  - Drop Python < 3.9
- Drop deprecated implicit conversion in ResampleStream

~~Python 3.13 RC is planned in July, so there will be no new release until then.~~

~~If you are urgent with NumPy 2 support, try [v0.4.0b1](https://pypi.org/project/soxr/0.4.0b1/).~~

**Comment by dofuuz** [comment]
It seems like Python-SoXR is blocking many dependencies. I'll just bump v0.4.0b1 to v0.4.0 to solve this now.

**Comment by dofuuz** [comment]
Next release plan issue is moved to #30.

**Comment by bmcfee** [comment]
Excellent! :rocket:
