### ISSUE TITLE
conda-forge packaging

### ISSUE THREAD

**Issue by bmcfee** [dofuuz/python-soxr#6]
:wave: @dofuuz are you at all interested in providing a conda-forge package for this library?

libsoxr itself is already available https://anaconda.org/conda-forge/soxr so there shouldn't be any significant barrier here.

The main benefit of conda-forge packaging this library would be ease of installation and management for downstream projects (eg librosa).

**Comment by dofuuz** [comment]
https://github.com/conda-forge/staged-recipes/pull/19495
I made PR to conda-forge.

**Comment by dofuuz** [comment]
PR for conda-forge is kind of rejected for now.

Actually, python-soxr is using static link for easy installation, so does not need separate libsoxr .
Conda-forge maintainer is requesting (optional) dynamic linking libsoxr. So, it's not likely to be merged into conda-forge for now.

**Comment by bmcfee** [comment]
> Actually, python-soxr is using static link for easy installation, so does not need separate libsoxr .

I followed that discussion over on the conda-forge PR, but I didn't understand why this has to be static only?  As noted over there, conda packages are cross-language, so a dynamic linkage here ought to be fine (preferred even).  Seems to me like you can have a static build for pypi and a dynamic build for the conda-forge recipe without causing any major trouble.

**Comment by dofuuz** [comment]
@bmcfee Yes, that's right. I'm just quite lazy for implement it. 😉
I'll handle this in near future.

**Comment by dofuuz** [comment]
Python-SoXR is now on conda-forge.
https://anaconda.org/conda-forge/soxr-python

**Comment by bmcfee** [comment]
Awesome! :tada:
